name: Validate .txt Files

on:
  push:
    branches: [ firstbranch ]
  pull_request:
    branches: [ firstbranch ]

jobs:
  check-txt-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List .txt files
      run: |
        echo "Listing all .txt files:"
        find . -type f -name "*.txt"

    - name: Check required .txt files
      run: |
        REQUIRED_FILES=("App.txt" "AppDbContext.txt" "Customer.txt" "CustomerOrder.txt")
        for FILE in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$FILE" ]; then
            echo "❌ $FILE is missing!"
            exit 1
          else
            echo "✅ $FILE exists."
          fi
        done
